;;; md-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from md-ts-mode.el

(autoload 'md-ts-mode "md-ts-mode" "\
Major mode for editing Markdown using tree-sitter grammar.

(fn)" t)
(autoload 'md-ts-mode-maybe "md-ts-mode" "\
Enable `md-ts-mode' when its grammar is available.")
(autoload 'md-ts-mode-enable-global "md-ts-mode" "\
Explicitly prefer `md-ts-mode' for Markdown buffers globally.

This is safe to call from user init files and is idempotent.
It adds a `\\.md\\' entry to `auto-mode-alist', remaps
`markdown-mode' through `major-mode-remap-alist', and, when the
built-in `markdown-ts-mode' is available, remaps that mode too.")
(register-definition-prefixes "md-ts-mode" '("md-ts-"))

;;; End of scraped data

(provide 'md-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; md-ts-mode-autoloads.el ends here
