;;; ada-ts-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from ada-ts-casing.el

(put 'ada-ts-mode-case-formatting 'safe-local-variable (lambda (rules) (while (and (consp rules) (consp (car rules)) (not (unsafep (list (plist-get (cdar rules) :formatter))))) (setq rules (cdr rules))) (null rules)))
(register-definition-prefixes "ada-ts-casing" '("ada-ts-"))


;;; Generated autoloads from ada-ts-indentation.el

(put 'ada-ts-mode-indent-backend 'safe-local-variable #'symbolp)
(put 'ada-ts-mode-indent-offset 'safe-local-variable #'integerp)
(register-definition-prefixes "ada-ts-indentation" '("ada-ts-"))


;;; Generated autoloads from ada-ts-mode.el

(autoload 'ada-ts-mode "ada-ts-mode" "\
Major mode for editing Ada, powered by tree-sitter.

In addition to any hooks its parent mode `prog-mode' might have run, this mode runs the
hook `ada-ts-mode-hook', as the final or penultimate step during initialization.

\\{ada-ts-mode-map}" t)
(add-to-list 'auto-mode-alist `(,(rx (or ".ada" ".adb" ".ads" ".adc") eos) . ada-ts-mode))
(when (fboundp 'derived-mode-add-parents) (derived-mode-add-parents 'ada-ts-mode '(ada-mode)))
(if (boundp 'major-mode-remap-defaults) (add-to-list 'major-mode-remap-defaults '(ada-mode . ada-ts-mode)) (add-to-list 'major-mode-remap-alist '(ada-mode . ada-ts-mode)))
(register-definition-prefixes "ada-ts-mode" '("ada-ts-mode-"))


;;; Generated autoloads from ada-ts-mode-lspclient.el

(register-definition-prefixes "ada-ts-mode-lspclient" '("ada-ts-mode-lspclient-"))


;;; Generated autoloads from ada-ts-mode-lspclient-eglot.el

(with-eval-after-load 'ada-ts-mode (with-eval-after-load 'eglot (require 'ada-ts-mode-lspclient-eglot)))
(register-definition-prefixes "ada-ts-mode-lspclient-eglot" '("ada-ts-mode-lspclient-eglot"))


;;; Generated autoloads from ada-ts-mode-lspclient-lsp-mode.el

(with-eval-after-load 'ada-ts-mode (with-eval-after-load 'lsp-mode (require 'ada-ts-mode-lspclient-lsp-mode)))
(register-definition-prefixes "ada-ts-mode-lspclient-lsp-mode" '("ada-ts-mode-lspclient-" "lsp-clients"))

;;; End of scraped data

(provide 'ada-ts-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; ada-ts-mode-autoloads.el ends here
