;;; solidity-mode-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from solidity-common.el

(register-definition-prefixes "solidity-common" '("solidity-sol"))


;;; Generated autoloads from solidity-mode.el

(add-to-list 'auto-mode-alist '("\\.sol\\'" . solidity-mode))
(autoload 'solidity-mode "solidity-mode" "\
Major mode for editing solidity language buffers.

(fn)" t)
(register-definition-prefixes "solidity-mode" '("solidity-"))

;;; End of scraped data

(provide 'solidity-mode-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; solidity-mode-autoloads.el ends here
