;;; org-present-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from org-present.el

(autoload 'org-present "org-present" "\
Start org presentation." t)
(register-definition-prefixes "org-present" '("org-present-"))

;;; End of scraped data

(provide 'org-present-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8-emacs-unix
;; End:

;;; org-present-autoloads.el ends here
