;;; acp-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from acp.el

(register-definition-prefixes "acp" '("acp-"))


;;; Generated autoloads from acp-fakes.el

(register-definition-prefixes "acp-fakes" '("acp-fakes-"))


;;; Generated autoloads from acp-traffic.el

(register-definition-prefixes "acp-traffic" '("acp-traffic-"))

;;; End of scraped data

(provide 'acp-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; acp-autoloads.el ends here
