;;; stickies-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from stickies.el

(autoload 'stickies-note-mode "stickies" "\
Minor mode for buffers that are sticky notes.

Applies the buffer's theme colors via a `default' face remap,
hides the mode line, installs a header line with a close button,
binds `mouse-3' to a context menu for changing themes, and closes
the corresponding sticky note frame when the buffer is killed.

This is a minor mode.  If called interactively, toggle the
`Stickies-Note mode' mode.  If the prefix argument is positive, enable
the mode, and if it is zero or negative, disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate the variable `stickies-note-mode'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

\\{stickies-note-mode-map}

(fn &optional ARG)" t)
(autoload 'stickies-new "stickies" "\
Create a new sticky note in `stickies-directory' and open it.
The filename is chosen automatically; use `stickies-rename' to
rename it afterwards." t)
(autoload 'stickies-open "stickies" "\
Open the sticky note BASENAME from `stickies-directory'.

(fn BASENAME)" t)
(autoload 'stickies-show-all "stickies" "\
Show every sticky note in `stickies-directory'.
Only supported on graphical frames." t)
(autoload 'stickies-hide-all "stickies" "\
Hide every visible sticky note frame.
Only supported on graphical frames." t)
(autoload 'stickies-toggle "stickies" "\
Toggle the visibility of all sticky notes.
If the current frame is itself a sticky note, hide every sticky note.
Otherwise show every sticky note in `stickies-directory' and raise the
frames.  Dispatching on the current frame instead of overall
visibility means one invocation from a non-sticky note frame always
brings the sticky notes forward, even when some are merely occluded
by other windows -- something Emacs has no API to detect.

Only supported on graphical frames." t)
(autoload 'stickies-set-theme "stickies" "\
Set NAME as the theme for the current sticky note.

(fn NAME)" t)
(autoload 'stickies-rename "stickies" "\
Rename the current sticky note to NEW-BASENAME (within `stickies-directory').

(fn NEW-BASENAME)" t)
(autoload 'stickies--note-blank-p "stickies" "\
Return non-nil if note BUFFER holds nothing but whitespace.

(fn BUFFER)")
(register-definition-prefixes "stickies" '("stickies-"))

;;; End of scraped data

(provide 'stickies-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; stickies-autoloads.el ends here
