;;; pi-coding-agent-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from md-ts-mode.el

(autoload 'md-ts-mode "md-ts-mode" "\
Major mode for editing Markdown using tree-sitter grammar.

In addition to any hooks its parent mode `text-mode' might have run, this mode runs the
hook `md-ts-mode-hook', as the final or penultimate step during initialization.

\\{md-ts-mode-map}" t)
(autoload 'md-ts-mode-maybe "md-ts-mode" "\
Enable `md-ts-mode' when its grammar is available.
This helper is for explicit user configuration; loading the bundled
mode does not register global Markdown file associations or remaps.")
(register-definition-prefixes "md-ts-mode" '("md-ts-"))


;;; Generated autoloads from pi-coding-agent.el

(autoload 'pi-coding-agent "pi-coding-agent" "\
Start or switch to pi coding agent session in current project.
With prefix arg, prompt for SESSION name to allow multiple sessions.
If already in a pi buffer and no SESSION specified, ensures this session
is visible. When both chat and input are already shown in the current
frame, keeps layout unchanged and focuses the input window.

(fn &optional SESSION)" t)
(autoload 'pi-coding-agent-toggle "pi-coding-agent" "\
Toggle pi coding agent window visibility for the current project.
If pi windows are visible in the current frame, hide them.
If hidden there but a session exists, show them.
If no session exists, signal an error." t)
(register-definition-prefixes "pi-coding-agent" '("pi-coding-agent--setup-session"))


;;; Generated autoloads from pi-coding-agent-core.el

(register-definition-prefixes "pi-coding-agent-core" '("pi-coding-agent-"))


;;; Generated autoloads from pi-coding-agent-grammars.el

(autoload 'pi-coding-agent-install-grammars "pi-coding-agent-grammars" "\
Show grammar status and install missing tree-sitter grammars.
Displays which grammars are installed and which are missing,
then offers to install the missing ones." t)
(register-definition-prefixes "pi-coding-agent-grammars" '("pi-coding-agent-"))


;;; Generated autoloads from pi-coding-agent-input.el

(register-definition-prefixes "pi-coding-agent-input" '("pi-coding-agent-"))


;;; Generated autoloads from pi-coding-agent-menu.el

(autoload 'pi-coding-agent-new-session "pi-coding-agent-menu" "\
Start a new pi session (reset)." t)
(autoload 'pi-coding-agent-reload "pi-coding-agent-menu" "\
Reload the current session by restarting the pi process.
Useful for reloading extensions, skills, prompts, and themes after
editing them, or when the pi process has died or become unresponsive.
Kills any existing process and starts fresh, then resumes the session
using the cached session file." t)
(register-definition-prefixes "pi-coding-agent-menu" '("pi-coding-agent-"))


;;; Generated autoloads from pi-coding-agent-render.el

(register-definition-prefixes "pi-coding-agent-render" '("pi-coding-agent-"))


;;; Generated autoloads from pi-coding-agent-ui.el

(register-definition-prefixes "pi-coding-agent-ui" '("pi-coding-agent-"))

;;; End of scraped data

(provide 'pi-coding-agent-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; pi-coding-agent-autoloads.el ends here
