#+TITLE: macOS emacs-like key bindings
#+STARTUP: showall

On macOS, default key bindings for text input can be set using a config file.
You can read more about this at https://www.hcs.harvard.edu/~jrus/site/cocoa-text.html

# /* This property list has not been converted to XML because XML
#  * key-binding files are really nasty to try to read in a text editor...
#  * PropertyListEditor using the "Show Strings as ASCII" option does OK,
#  * but even that will put in real carriage returns and tabs and stuff
#  * instead of backslash escape sequences and you also lose the useful
#  * comments that way.
#  */
#
# /* When editing this file remember to be carefull with your syntax.
#  * If you forget a semicolon or inadvertently insert a
#  * control-character (due to testing while editing this file in
#  * TextEdit, for example) then this file will be silently ignored and
#  * can lead to puzzling behaviour while testing changes.
#  */

#+BEGIN_SRC text :noweb yes :mkdirp yes :tangle ~/Library/KeyBindings/DefaultKeyBinding.dict
  {
      "~f"      = "moveWordForward:";        /* M-f */
      "~b"      = "moveWordBackward:";       /* M-b */
      "~<"      = "moveToBeginningOfDocument:";  /* M-< */
      "~>"      = "moveToEndOfDocument:";    /* M-> */
      "~v"      = "pageUp:";                 /* M-v */
      "^v"      = "pageDown:";               /* C-v */
      "~d"      = "deleteWordForward:";      /* M-d */
      "~^h"     = "deleteWordBackward:";     /* M-C-h */
      "~\010"   = "deleteWordBackward:";     /* M-backspace */
      "~\177"   = "deleteWordBackward:";     /* M-delete */
      "~\UF728" = "deleteWordForward:";      /* delete */
      "\UF729"  = "moveToBeginningOfDocument:";  /* home */
      "\UF72B"  = "moveToEndOfDocument:";        /* end */
      "@\UF729" = "moveToBeginningOfParagraph:"; /* A-home */
      "@\UF72B" = "moveToEndOfParagraph:";       /* A-end */
      "@\UF700" = "moveToBeginningOfDocument:";  /* A-up */
      "@\UF701" = "moveToEndOfDocument:";    /* A-down */
      "^\UF700" = "pageUp:";                 /* C-up */
      "^\UF701" = "pageDown:";               /* C-down */
      "\UF72C"  = "pageUp:";                 /* page-up */
      "\UF72D"  = "pageDown:";               /* page-down */
      "^/"      = "undo:";                   /* C-/ */
      "^_"      = "undo:";                   /* C-_ */
      "~c"      = "capitalizeWord:";         /* M-c */
      "~u"      = "uppercaseWord:";          /* M-u */
      "~l"      = "lowercaseWord:";          /* M-l */
      "^t"      = "transpose:";              /* C-t */
      "~t"      = "transposeWords:";         /* M-t */
      "~/"      = "complete:";               /* M-/ */
      "^g"      = "_cancelKey:";             /* F5 */
      "^a"      = "moveToBeginningOfLine:";  /* C-a */
      "^e"      = "moveToEndOfLine:";        /* C-e */

      /* Bind some ^x combos. */
      "^x" = {
          "^x" = "swapWithMark:";            /* C-x C-x */
          "^m" = "selectToMark:";            /* C-x C-m */
          "^s" = "save:";                    /* C-x C-s */
          "^w" = "saveAs:";                  /* C-x C-w */
      };

      /* Mark-point stuff (Emacs-style mark and point bindings are
       * implemented but not bound by default.  In the text system the
       * mark and point are ranges, not just locations.  The "point" is
       * the selected range.)
       */
      "^@" = "setMark:";                     /* C-@ */
      "^ " = "setMark:";                     /* C-space */
      "^w" = "deleteToMark:";                /* C-w */

      "^j" = "insertNewline:";               /* C-j */
      "^i" = "insertTab:";                   /* C-i */
  }
#+END_SRC
