;;; compat-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (directory-file-name
                         (or (file-name-directory #$) (car load-path))))



;;; Generated autoloads from compat-27.el

(register-definition-prefixes "compat-27" '("derived-mode-p"))


;;; Generated autoloads from compat-help.el

(register-definition-prefixes "compat-help" '("compat---describe"))


;;; Generated autoloads from compat-macs.el

(register-definition-prefixes "compat-macs" '("compat-"))

;;; End of scraped data

(provide 'compat-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; coding: utf-8-emacs-unix
;; End:

;;; compat-autoloads.el ends here
